# Generated by Django 4.1.3 on 2022-12-18 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Konstitsiya_Bob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.PositiveSmallIntegerField()),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Konstitsiya_Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.PositiveSmallIntegerField()),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=40)),
                ('parol', models.CharField(max_length=25)),
                ('nomer', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Site_Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('batafsil', models.CharField(max_length=100)),
                ('rasm', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Konstitsiya_Modda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.PositiveSmallIntegerField()),
                ('matn', models.TextField()),
                ('bobFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.konstitsiya_bob')),
            ],
        ),
        migrations.AddField(
            model_name='konstitsiya_bob',
            name='bolimFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.konstitsiya_bolim'),
        ),
        migrations.CreateModel(
            name='Izohlar_Site_Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh', models.CharField(max_length=150)),
                ('vaqti', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
