# Generated by Django 4.1.3 on 2022-12-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konstitsiya_modda',
            name='bolimFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.konstitsiya_bolim'),
        ),
        migrations.AlterField(
            model_name='konstitsiya_modda',
            name='bobFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.konstitsiya_bob'),
        ),
    ]
